pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/
    - cp style.css public/
    - cp main.js public/
    - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - main
